@base_url = http://localhost:8080

### Get All AB Tests
GET {{base_url}}/api/ab-tests

### Create AB Test
POST {{base_url}}/api/ab-tests
Content-Type: application/json

{
  "gaSessionId": "ga_abc123",
  "test": 1,
  "testGroup": 1
}

### Get AB Tests by Session ID
GET {{base_url}}/api/ab-tests/session/ga_abc123