@base_url = http://localhost:8080

### Get All Email Visit
GET {{base_url}}/api/email-visit

### Get Email Visit by ID
GET {{base_url}}/api/email-visit/1

### Create Email Visit
POST {{base_url}}/api/email-visit
Content-Type: application/json

{
  "id": 1001,
  "idAccount": 5,
  "visitDate": "2026-01-15",
  "visitTimestamp": "2026-01-15T11:00:00"
}

### Update Email Visit
PUT {{base_url}}/api/email-visit/1001
Content-Type: application/json

{
  "id": 1001,
  "idAccount": 5,
  "visitDate": "2026-01-20",
  "visitTimestamp": "2026-01-20T12:00:00"
}

### Delete Email Visit
DELETE {{base_url}}/api/email-visit/1001

### Get Email Visit by Account ID
GET {{base_url}}/api/email-visit/account/5